eureka:  client:    register-with-eureka: true
    fetch-registry: true
  instance:    prefer-ip-address: true
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:  cloud:    config:      profile: dev      
server:
  port: 8750