spring:
  application:
    name: employee-config-server  cloud:    config:      server:        git:          uri: https://github.com/repotec/employee-sample-microservice/tree/master/config-repo
    
server:  port: 8763
  